language: php

php:
  - 7.0
  - 7.1

sudo: false

# prevent hhvm from running the tests in isolation, since they take ages
matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: hhvm
  fast_finish: true

before_script:
  - composer install --ignore-platform-reqs
  - mkdir -p build/logs
script: php test/run-tests.php

after_success:
  - travis_retry php vendor/bin/coveralls --coverage_clover=build/logs/coverage.xml
